/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package speedeatsof.vista.Principal;

import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author juanR
 */
public class inicioSesion extends javax.swing.JPanel {

    /**
     * Creates new form inicioSesion
     */
    public inicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtcorreoi = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtcontrai = new javax.swing.JPasswordField();
        btninicio = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(500, 590));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speedeatsof/resources/userL.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Correo Electronico");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Contraseña");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 392, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 450, 12));

        txtcorreoi.setText("carlos@gmail.com");
        txtcorreoi.setBorder(null);
        txtcorreoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorreoiActionPerformed(evt);
            }
        });
        add(txtcorreoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 286, 450, 24));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 450, 12));

        txtcontrai.setBorder(null);
        add(txtcontrai, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 450, 30));

        btninicio.setBackground(new java.awt.Color(102, 102, 255));
        btninicio.setForeground(new java.awt.Color(255, 255, 255));
        btninicio.setText("Iniciar Sesión");
        add(btninicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 140, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txtcorreoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorreoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btninicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField txtcontrai;
    private javax.swing.JTextField txtcorreoi;
    // End of variables declaration//GEN-END:variables

    public JButton getBtninicio() {
        return btninicio;
    }

    public JPasswordField getTxtcontrai() {
        return txtcontrai;
    }

    public JTextField getTxtcorreoi() {
        return txtcorreoi;
    }

    
    
}
