/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package speedeatsof.vista.Administrador;

import java.awt.BorderLayout;
import speedeatsof.control.ControladorEspacios;
import speedeatsof.control.ControladorPedido;
import speedeatsof.control.ControladorProducto;
import speedeatsof.logica.Usuarios;
import speedeatsof.vista.Principal.VentanaPrincipal;

/**
 *
 * @author juanR
 */
public class VentanaAdministrador extends javax.swing.JFrame {

    private UsuariosPanel up;
    private ProductosPanel pp;
    private EspaciosPanel ep;
    private InformesPanel ip;
    private static VentanaAdministrador instancia;
    private Usuarios usuarioLogueado;
    private ControladorProducto controlproducto;
    private ControladorEspacios controlespacio;
    private ControladorPedido controlpedido;
    
    public VentanaAdministrador() {
        initComponents();
        this.up = new UsuariosPanel();
        this.pp = new ProductosPanel();
        this.ep = new EspaciosPanel();
        this.ip = new InformesPanel();
        
        
    }
    
    public static VentanaAdministrador getInstancia() {
        if (instancia == null) {
            instancia = new VentanaAdministrador();
        }
        return instancia;
    }

    public void setUsuarioLogueado(Usuarios usuarioLogueado) {
        this.usuarioLogueado = usuarioLogueado;
        labelA.setText(usuarioLogueado.getNombre()+" "+usuarioLogueado.getApellido());
        // Aquí puedes actualizar elementos de la interfaz con los datos del usuario
    }

    public UsuariosPanel getUp() {
        return up;
    }

    public ProductosPanel getPp() {
        return pp;
    }

    public EspaciosPanel getEp() {
        return ep;
    }

    public InformesPanel getIp() {
        return ip;
    }
    
    
    
    public void resetear() {
        usuarioLogueado = null;
        // Resetear componentes si es necesario
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnProductos = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnEspacios = new javax.swing.JButton();
        btnInformes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        labelA = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ContentA = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProductos.setBackground(new java.awt.Color(255, 0, 0));
        btnProductos.setText("Productos");
        btnProductos.setBorder(null);
        btnProductos.setBorderPainted(false);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        jPanel2.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 0, 70, 60));

        btnUsuarios.setBackground(new java.awt.Color(255, 0, 0));
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setBorder(null);
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jPanel2.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 60, 60));

        btnEspacios.setBackground(new java.awt.Color(255, 0, 0));
        btnEspacios.setText("Espacios");
        btnEspacios.setBorder(null);
        btnEspacios.setBorderPainted(false);
        btnEspacios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspaciosActionPerformed(evt);
            }
        });
        jPanel2.add(btnEspacios, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 60, 60));

        btnInformes.setBackground(new java.awt.Color(255, 0, 0));
        btnInformes.setText("Informes");
        btnInformes.setBorder(null);
        btnInformes.setBorderPainted(false);
        btnInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformesActionPerformed(evt);
            }
        });
        jPanel2.add(btnInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speedeatsof/resources/logo icon.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 60));

        btnCerrarSesion.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speedeatsof/resources/cerrar sesion.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, -7, 120, 70));

        labelA.setText("Usuario...");
        jPanel2.add(labelA, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, -1));

        jLabel3.setText("Administrador");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1012, -1));

        ContentA.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Bienvenido al Menu de administrador:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Opciones del Sistema:");

        jLabel6.setText("-Gestion de usuarios(permisos de super usuario).");

        jLabel7.setText("-Gestion de Productos:");

        jLabel8.setText("-Gestion de Espacios(mesas y barras)");

        jLabel9.setText("-Informes detallados.");

        javax.swing.GroupLayout ContentALayout = new javax.swing.GroupLayout(ContentA);
        ContentA.setLayout(ContentALayout);
        ContentALayout.setHorizontalGroup(
            ContentALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentALayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(ContentALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap(668, Short.MAX_VALUE))
        );
        ContentALayout.setVerticalGroup(
            ContentALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentALayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(0, 164, Short.MAX_VALUE))
        );

        getContentPane().add(ContentA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 61, 1010, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        up.setSize(1010, 470);
        up.setLocation(0, 0);
        ContentA.removeAll();
        ContentA.add(up, BorderLayout.CENTER);
        ContentA.revalidate();
        ContentA.repaint();
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        VentanaPrincipal p= VentanaPrincipal.getInstancia();
        p.setVisible(true);
        resetear();
        dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        pp.setSize(1010, 470);
        pp.setLocation(0, 0);
        ContentA.removeAll();
        ContentA.add(pp, BorderLayout.CENTER);
        ContentA.revalidate();
        ContentA.repaint();
        this.controlproducto = new ControladorProducto();
        
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnEspaciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspaciosActionPerformed
        ep.setSize(1010, 470);
        ep.setLocation(0, 0);
        ContentA.removeAll();
        ContentA.add(ep, BorderLayout.CENTER);
        ContentA.revalidate();
        ContentA.repaint();
        this.controlespacio = new ControladorEspacios();
    }//GEN-LAST:event_btnEspaciosActionPerformed

    private void btnInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformesActionPerformed
        ip.setSize(1010, 470);
        ip.setLocation(0, 0);
        ContentA.removeAll();
        ContentA.add(ip, BorderLayout.CENTER);
        ContentA.revalidate();
        ContentA.repaint();
        this.controlpedido = ControladorPedido.getInstancia();
    }//GEN-LAST:event_btnInformesActionPerformed

   
    

    public void habilitarOpcionesSuperUsuario(Usuarios usuarioLogueado) {
        
        if("Administrador".equals(usuarioLogueado.getRol()) && usuarioLogueado.isIs_su()){
          btnUsuarios.setEnabled(true);  
        }else{
           btnUsuarios.setEnabled(false);  
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentA;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEspacios;
    private javax.swing.JButton btnInformes;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelA;
    // End of variables declaration//GEN-END:variables
}
